namespace Citrine
{
    enum MinecraftBedrockGamePackageStatus {

        NotInstalled,
        PreparingDownload,
        Downloading,
        Extracting,
        CancellingInstallation,
        InstallationPaused,
        InstallationFailed,
        Installed,
        PreparingRepair,
        Repairing,
        RepairFailed,
        Registering,
        Launching,
        Unregistering,
        Uninstalling,
        UninstallationPending,
        UninstallationFailed,
    };
}