import "Collections/IObservableCollectionView.idl";
import "Collections/IItemFilter.idl";

namespace Citrine
{
    interface IFilterableCollectionView requires IVectorView<Object>, Microsoft.UI.Xaml.Interop.INotifyCollectionChanged
    {
        Boolean IsEmpty{ get; };

        IObservableCollectionView Source{ get; };
        String Filter;
        IItemFilter SecondaryFilter;
        void Refresh();
        void Refresh(Object mutatedItem);

        Windows.UI.Xaml.Interop.TypeName ItemType{ get; };
    }
}