namespace Citrine
{
    [default_interface]
    runtimeclass MinecraftBedrockInstallLocationPicker 
    {
        MinecraftBedrockInstallLocationPicker();
    
        Microsoft.UI.Xaml.XamlRoot XamlRoot;
        
        String DefaultInstallLocation;
        String PickInstallLocation();
    }
}
