import "UI/Views/Pages/MinecraftBedrockGamePackagesPage.idl";

namespace Citrine
{
    [default_interface]
    runtimeclass MinecraftBedrockReleasesPage : MinecraftBedrockGamePackagesPage
    {
        MinecraftBedrockReleasesPage();
    }
}
