import "UI/Views/Pages/MinecraftBedrockGamePackagesPage.idl";

namespace Citrine
{
    [default_interface]
    runtimeclass MinecraftBedrockPreviewsPage : MinecraftBedrockGamePackagesPage
    {
        MinecraftBedrockPreviewsPage();
    }
}
