#pragma once

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define CITRINE_STRINGIFY_VALUE(x) #x
#define CITRINE_STRINGIFY(x) CITRINE_STRINGIFY_VALUE(x)

#define CITRINE_VERSION_MAJOR			0
#define CITRINE_VERSION_MINOR			2
#define CITRINE_VERSION_PATCH			0

#define CITRINE_FILEVERSION				CITRINE_VERSION_MAJOR, CITRINE_VERSION_MINOR, CITRINE_VERSION_PATCH, 0
#define CITRINE_PRODUCTVERSION			CITRINE_STRINGIFY(CITRINE_VERSION_MAJOR) "." \
										CITRINE_STRINGIFY(CITRINE_VERSION_MINOR) "." \
										CITRINE_STRINGIFY(CITRINE_VERSION_PATCH)

#define IDI_CITRINE_ICON				1
