namespace Citrine
{
    [default_interface]
    runtimeclass GeneralSettingsViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        GeneralSettingsViewModel();

        Int32 Theme;
        Int32 Backdrop;

        IVector<IInspectable> Languages{ get; };
        Int32 Language;
        Boolean LanguageHasChanged{ get; };

        Boolean AutomaticUpdateChecks;
        Int32 UpdateChannel;

        Microsoft.UI.Xaml.Input.ICommand RestartAppCommand{ get; };
        Microsoft.UI.Xaml.Input.ICommand OpenAppDataDirectoryCommand{ get; };
    }
}
