namespace Citrine
{
    [default_interface]
    runtimeclass ProgressBarExTemplateSettings : Microsoft.UI.Xaml.DependencyObject
    {
        Double ContainerAnimationStartPosition{ get; };
        Double ContainerAnimationEndPosition{ get; };
        Double Container2AnimationStartPosition{ get; };
        Double Container2AnimationEndPosition{ get; };
        Double ContainerAnimationMidPosition{ get; };
        Double IndicatorLengthDelta{ get; };
        Microsoft.UI.Xaml.Media.RectangleGeometry ClipRect{ get; };

        static Microsoft.UI.Xaml.DependencyProperty ContainerAnimationStartPositionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ContainerAnimationEndPositionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty Container2AnimationStartPositionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty Container2AnimationEndPositionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ContainerAnimationMidPositionProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IndicatorLengthDeltaProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ClipRectProperty{ get; };
    }
}
