namespace Citrine
{
    [contentproperty("WindowContent")]
    [default_interface]
    unsealed runtimeclass WindowEx : Microsoft.UI.Xaml.Window
    {
        WindowEx();
        IInspectable WindowContent;
    }
}
